default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bookmyshow
  host: localhost
  username: rails
  password: rails

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>